/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Laboratorio-Info
 */
public class Menu_DAO extends javax.swing.JFrame {

    /**
     * Creates new form Menu_DAO
     */
    public Menu_DAO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fechar = new javax.swing.JButton();
        receita_btn = new javax.swing.JButton();
        declaracao_btn = new javax.swing.JButton();
        atestado_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        fechar.setText("x");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });
        jPanel1.add(fechar);
        fechar.setBounds(359, 10, 50, 23);

        receita_btn.setText("Receita");
        receita_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receita_btnActionPerformed(evt);
            }
        });
        jPanel1.add(receita_btn);
        receita_btn.setBounds(140, 120, 110, 23);

        declaracao_btn.setText("Declaração");
        declaracao_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declaracao_btnActionPerformed(evt);
            }
        });
        jPanel1.add(declaracao_btn);
        declaracao_btn.setBounds(140, 190, 110, 23);

        atestado_btn.setText("Atestado");
        atestado_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atestado_btnActionPerformed(evt);
            }
        });
        jPanel1.add(atestado_btn);
        atestado_btn.setBounds(140, 50, 110, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(429, 283));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fecharActionPerformed

    private void atestado_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atestado_btnActionPerformed
        try {
            Controller.Funcoes_DAO.atestado();
        } catch (Exception ex) {
            Logger.getLogger(Menu_DAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atestado_btnActionPerformed

    private void receita_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receita_btnActionPerformed
        try {
            Controller.Funcoes_DAO.receita();
        } catch (Exception ex) {
            Logger.getLogger(Menu_DAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_receita_btnActionPerformed

    private void declaracao_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declaracao_btnActionPerformed
        try {
            Controller.Funcoes_DAO.declaracao();
        } catch (Exception ex) {
            Logger.getLogger(Menu_DAO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_declaracao_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_DAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atestado_btn;
    private javax.swing.JButton declaracao_btn;
    private javax.swing.JButton fechar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton receita_btn;
    // End of variables declaration//GEN-END:variables
}
